# Generated by Django 5.2.1 on 2025-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_bank',
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default='TRX12345678', max_length=25),
        ),
    ]
