# Generated by Django 5.2.1 on 2025-05-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0005_remove_transaction_recipient_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(default='', max_length=20),
        ),
    ]
