# Generated by Django 5.2.1 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0006_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
