# Generated by Django 5.2.1 on 2025-05-31 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0007_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2030, 5, 31)),
        ),
    ]
