# Generated by Django 5.2.1 on 2025-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0008_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cnic',
            field=models.CharField(default='', max_length=30),
        ),
    ]
