# Generated by Django 5.2.1 on 2025-05-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0009_card_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='779', max_length=3),
        ),
    ]
