# Generated by Django 5.2.1 on 2025-05-31 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0010_alter_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='365', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateField(default=datetime.date(2025, 5, 31)),
        ),
    ]
