# Generated by Django 5.2.1 on 2025-06-01 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0011_alter_card_cvv_alter_card_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='atm_withdrawal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='online_tran',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='293', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2030, 6, 1)),
        ),
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateField(default=datetime.date(2025, 6, 1)),
        ),
    ]
