# Generated by Django 5.2.1 on 2025-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0012_card_atm_withdrawal_card_online_tran_alter_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='735', max_length=3),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
