# Generated by Django 5.2.1 on 2025-06-02 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0013_alter_card_cvv_delete_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='184', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2030, 6, 2)),
        ),
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateField(default=datetime.date(2025, 6, 2)),
        ),
    ]
